### ISSUE TITLE
Unrecognized option: --sql-type=insert

### ISSUE THREAD

**Issue by zmix999** [zhuchao941/canal2sql#2]
没有--sql-type参数
![image](https://github.com/zhuchao941/canal2sql/assets/135001258/97b58081-b194-4481-bcb8-5272e21e5574)

**Comment by zmix999** [comment]
![image](https://github.com/zhuchao941/canal2sql/assets/135001258/810d9753-1fc3-483a-8aa7-9c048fdc4a42)
![image](https://github.com/zhuchao941/canal2sql/assets/135001258/83cf1030-0c1b-40e9-8637-89d5ef25202e)
jar包是不是传错了

**Comment by zhuchao941** [comment]
收到。
1. sql_type支持有点问题
2. jar包没传错的 只是里面的usage版本号目前写死的 这个我也优化下

**Comment by zhuchao941** [comment]
fix with version 1.1.1
