### ISSUE TITLE
在线模式是否可增加持久化配置，到将输出内容保存到本地文件或者数据库中

### ISSUE THREAD

**Issue by pengwenkang7** [zhuchao941/canal2sql#4]
个人感觉实时在线模式很好用，有个想法是针对比较重要的数据库，通过长期后台运行保存最近几天的binlog解析出的sql和恢复sql，在出问题时可提高恢复速度，不用再去找对应的时间点和pos参数，通过搜索有问题的sql找到恢复的sql。仅供建议哈。

**Comment by zhuchao941** [comment]
本项目旨在做一个工具哈
不考虑长期运行哈 不然复杂性就要增加很多了 比如要考虑高可用 要考虑维护日志的完整性等等
你说的这种感觉放在canal-adapter里比较合适，增加一个plugin类型~
