### ISSUE TITLE
在线模式解析范围控制只使用-start_time、-end_time无法生成过去时间的回滚SQL

### ISSUE THREAD

**Issue by zitongchen** [zhuchao941/canal2sql#7]
作者你好，我使用 canal2sql 在线模式解析范围控制只使用 -start_time、-end_time 两个参数的时候，控制台无法输出过去时间的回滚SQL，过去时间范围的 binlog 文件是存在的。解析范围使用 -start_position、-end_position 是可以生成过去时间的回滚 SQL 的。请问是我用法上面有问题吗？还是属于工具的 Bug 呢？

**Comment by zhuchao941** [comment]
是的 属于bug 我尽快修复一下
